### PR TITLE
Fixes #205 and /f seepaypal

### LINKED ISSUE #205: Unclaim Radius doesn't work in 2.0-Development fork
**Describe the bug**
When you do /unclaim 5 it only unclaims the chunk you're standing in. This is beacuse instead of passing in the currentLocation variable from the SpiralTask it passes through the players current location.

To fix change line 55 from:
                    boolean success = unClaim(new FLocation(context.player), context);
To:
                    boolean success = unClaim(new FLocation(this.currentLocation()), context);

**To Reproduce**
1. Go to 'any claimed chunks'
2. Issue command '/f unclaim 5'
3. Notice it has only unclaimed the chunk you're standing in

**Expected behavior**
Should unclaim a radius and not just one chunk

**Server VErsion (please complete the following information):**
 - Spigot Version: 1.8.8
 - Factions Version v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC
 - Minecraft Version: 1.8

### PR DESCRIPTION
**Pull request by SvenjaReissaus**
Enslaved work

### CODE REVIEW

**Comment by prosavage** [comment]
Seems good.

File: src/main/java/com/massivecraft/factions/cmd/CmdUnclaim.java [hunk 1]
```diff
@@ -52,7 +52,7 @@ public void perform(CommandContext context) {
 
                 @Override
                 public boolean work() {
-                    boolean success = unClaim(new FLocation(context.player), context);
+                    boolean success = unClaim(currentFLocation(), context);
```
Comment (liz3) [inline src/main/java/com/massivecraft/factions/cmd/CmdUnclaim.java:55]: this null safe?
